### ISSUE TITLE
MathJax rendering difficult to read for dark mode

### ISSUE THREAD

**Issue by agkphysics** [Lightning-AI/torchmetrics#2831]
## 📚 Documentation

The MathJax equation renders using a dark foreground colour, so it is almost unreadable on a dark background:
![image](https://github.com/user-attachments/assets/73d8253c-2db8-49ae-9088-eecf2dc88a6b)

It seems to be related to inheriting the PyTorch theme which has the following section:
```css
article.pytorch-article .math {
  color: #262626;
  width: auto;
  text-align: center;
}
```

If you remove the `color` attribute using developer mode it becomes easily readable again:
![image](https://github.com/user-attachments/assets/299b0b2f-b7b0-4580-9e39-52a3f08bc252)
